# **Importing Libraries**

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# **Importing dataset**

In [4]:
dataset = pd.read_csv('/kaggle/input/student-performance-multiple-linear-regression/Student_Performance.csv')
dataset.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [5]:
dataset['Extracurricular Activities'] = dataset['Extracurricular Activities'].map({"Yes":1, "No":0})

In [6]:
dataset.head()

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0              7               99                           1            9   
1              4               82                           0            4   
2              8               51                           1            7   
3              5               52                           1            5   
4              7               75                           0            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [7]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
dataset = ss.fit_transform(dataset)

In [9]:
dataset

array([[ 0.77518771,  1.70417565,  1.01045465,  1.45620461, -1.24975394,
         1.86216688],
       [-0.38348058,  0.72391268, -0.98965352, -1.49229423, -0.90098215,
         0.50881766],
       [ 1.16141048, -1.06362569,  1.01045465,  0.27680507, -0.90098215,
        -0.5322202 ],
       ...,
       [ 0.38896495,  0.7815752 ,  1.01045465,  0.86650484,  0.1453332 ,
         0.9772847 ],
       [ 1.54763324,  1.5888506 ,  1.01045465,  0.27680507, -1.59852572,
         2.07037446],
       [ 0.77518771,  0.26261245, -0.98965352,  0.86650484, -1.24975394,
         0.45676577]])

In [13]:
X = dataset[:,:-1]
Y = dataset[:,-1]

array([ 1.86216688,  0.50881766, -0.5322202 , ...,  0.9772847 ,
        2.07037446,  0.45676577])

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y)

In [15]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,Y_train)

LinearRegression()

In [16]:
lr.predict(X_test)

array([ 0.36734798,  0.37946165,  0.06351848, ..., -1.68091372,
        0.63371418, -2.12825832])

In [19]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
ms = mean_squared_error(lr.predict(X_test),Y_test)
mb = mean_absolute_error(lr.predict(X_test),Y_test)
print(ms)
print(mb)

0.01100227920196342
0.0833375820475083


In [20]:
import pickle

with open("model.pkl","wb") as f:
    pickle.dump(lr,f)